### ISSUE TITLE
Doesn't work on A14 with KermelSU

### ISSUE THREAD

**Issue by firestarter7924** [mikropsoft/StevenBlock#13]
Hello
Trying to install it and get this error
Function not implemented (oc error 38)
Please help:(

**Comment by mikropsoft** [comment]
> Hello
> Trying to install it and get this error
> Function not implemented (oc error 38)
> Please help:(

Can you send a screenshot?

**Comment by firestarter7924** [comment]
Oh it's kernelsu...

**Comment by ask9027** [comment]
> Hello Trying to install it and get this error Function not implemented (oc error 38) Please help:(

Downgrde KernelSU Manager
