### ISSUE TITLE
Update problem in kernelsu

### ISSUE THREAD

**Issue by vnothkumar** [mikropsoft/StevenBlock#2]
![Screenshot_20240520-231032.png](https://github.com/mikropsoft/StevenBlock/assets/167418074/6cbb2eec-afdd-4578-90d0-22daae8256ca)

Fetch changelog failed.

**Comment by mikropsoft** [comment]
> ![Screenshot_20240520-231032.png](https://github.com/mikropsoft/StevenBlock/assets/167418074/6cbb2eec-afdd-4578-90d0-22daae8256ca)
> 
> 
> Fetch changelog failed.

Can you try again?

**Comment by vnothkumar** [comment]
Yes showing same error I updated manually

**Comment by mikropsoft** [comment]
> Yes showing same error so I updated manually 

Changelog.md file is empty so I thought that was the problem. No problem for Magisk but I will test for kernelsu for other devices. Thanks for the report.

**Comment by mikropsoft** [comment]
@vnothkumar Hello again,

I will post another update in a few days. Please let me know about this error. Also, I assume you are not using adaway, so you can uninstall the systemless hosts module. You do not need it.

**Comment by vnothkumar** [comment]
@mikropsoft 
Thanks for letting me know! I'll be on the lookout for your next update in a few days. I will let you know if I encounter the error again. You're right, I'm not using AdAway. I'll uninstall the systemless hosts module.

**Comment by vnothkumar** [comment]
@mikropsoft 

It sounds like the changelog issue you were experiencing has been resolved and everything is functioning properly now.

**Comment by mikropsoft** [comment]
> @mikropsoft 
> 
> It sounds like the changelog issue you were experiencing has been resolved and everything is functioning properly now.
> 

Btw, compatibility has improved with the changes I made to the previous version. Thanks again 😏
