### ISSUE TITLE
Add a way to add custom host sources

### ISSUE THREAD

**Issue by tukusejssirs** [mikropsoft/StevenBlock#3]
Could you add a way to add custom host sources (ideally as URLs) and merge them, ideally sync them daily, just like AdAway does it? It would be awesome IMHO. :pray:

**Comment by mikropsoft** [comment]
@tukusejssirs 

Hello again! I'm writing to keep you updated. I've now set up two separate hosts files for the module. There's no need to update the hosts file every month or week to block ads. If you're having issues with StevenBlack, you might want to try the 1hosts version—it could be the best option for blocking ads. (Though StevenBlack will still be updated more frequently.)
