### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [mikropsoft/StevenBlock#4]
May I ask what (FOSS-) license this project falls under? There's no license file in this repo, and the Readme doesn't mention it either. Thanks in advance!

**Comment by mikropsoft** [comment]
I am using a template, and just a simple code snippet is enough to apply this hosts file. My goal is to turn it into a module that stays constantly updated.

**Comment by IzzySoft** [comment]
Thanks @mikropsoft! Background of my question was that I had looked into adding your module to my repo with FOSS Magisk modules (https://apt.izzysoft.de/magisk). As this description states, only FOSS modules get in there – which would require a FOSS license (approved by OSI/FSF).

I of course respect your decision of not adding one. I had a similar situation many years ago with a project of mine, which was originally started by someone else who had given up on it. I didn't feel free to apply any license either then. Luckily in my case, I was able to reach the original dev and they agreed to the license I had chosen – not sure if you might have the same luck, though…

**Comment by mikropsoft** [comment]
> Thanks @mikropsoft! Background of my question was that I had looked into adding your module to my repo with FOSS Magisk modules (https://apt.izzysoft.de/magisk). As this description states, only FOSS modules get in there – which would require a FOSS license (approved by OSI/FSF).
> 
> I of course respect your decision of not adding one. I had a similar situation many years ago with a project of mine, which was originally started by someone else who had given up on it. I didn't feel free to apply any license either then. Luckily in my case, I was able to reach the original dev and they agreed to the license I had chosen – not sure if you might have the same luck, though…

Actually, that would be great. Since I don't really understand licensing well, I'm not sure what to do about it. Would it be problematic if I added an MIT license? Because I don't have much knowledge about licenses.

**Comment by IzzySoft** [comment]
FOSS licenses are going from very permissive (Apache, BSD, MIT) to very restrictive and complex (AGPL). MIT is easy to understand, so are most BSD ones: they have short and compact texts, you get it within 2..3 minutes. But try reading and understanding AGPL :see_no_evil:

I'm not a license expert. But yes, for this purpose MIT might be a good match. And it's approved by both, FSF and OSI (see the [license list here](https://spdx.org/licenses/)).

**Comment by mikropsoft** [comment]
> FOSS licenses are going from very permissive (Apache, BSD, MIT) to very restrictive and complex (AGPL). MIT is easy to understand, so are most BSD ones: they have short and compact texts, you get it within 2..3 minutes. But try reading and understanding AGPL :see_no_evil:
> 
> I'm not a license expert. But yes, for this purpose MIT might be a good match. And it's approved by both, FSF and OSI (see the [license list here](https://spdx.org/licenses/)).

The template uses the GNU General Public License v2.0. I guess using the same license won't be a problem! I will add it shortly.

**Comment by mikropsoft** [comment]
@IzzySoft

**Comment by IzzySoft** [comment]
Wonderful, thanks! Added your module to the repo then (will go live with the next sync later today):

![image](https://github.com/mikropsoft/StevenBlock/assets/6781438/28a8f73e-e984-4c2b-ab8c-324bfd52d903)

(in case you wonder about the "only" in `GPL-2.0-only`: that's as opposed to `GPL-2.0-or-later` had you [specified that](https://github.com/mikropsoft/StevenBlock/blob/main/LICENSE#L296). So its meaning is not "he had no better", but "stick to that version of the license" :wink:)

That said: this Magisk repo uses your `update.json` to check for new releases, whenever the update checker runs here, and then pulls what's specified there unless it's already here. Android clients supporting this repo include [MRepo](https://apt.izzysoft.de/packages/com.sanmer.mrepo) and [MMRL](https://apt.izzysoft.de/packages/com.dergoogler.mmrl).
