### ISSUE TITLE
YouTube history does not work

### ISSUE THREAD

**Issue by Zimty86** [mikropsoft/StevenBlock#5]
The YouTube history does not work. It is no longer displayed there

And I can't remember where I left off watching YouTube.

The problem is that S.youtube is blocked.

Is there any way to remove it?

I have tested the host editor but it can't save it.

**Comment by mikropsoft** [comment]
> The YouTube history does not work. It is no longer displayed there
> 
> And I can't remember where I left off watching YouTube.
> 
> The problem is that S.youtube is blocked.
> 
> Is there any way to remove it?
> 
> I have tested the host editor but it can't save it.

I will remove it and post it for the next updates, sir. I got a lot of complaints about it.

**Comment by mikropsoft** [comment]
Fixed on new release @Zimty86

**Comment by mikropsoft** [comment]
Hello again @Zimty86. If you continue to have problems, you can download the 1hosts version from the releases.

**Comment by ask9027** [comment]
s.youtube.com still in latest host file

**Comment by mikropsoft** [comment]
> `s.youtube.com` still in latest host file

@ask9027 Hello, you can use the 1hosts version available in previous versions.

**Comment by ask9027** [comment]
> > `s.youtube.com` still in latest host file
> 
> [@ask9027](https://github.com/ask9027) Hello, you can use the 1hosts version available in previous versions.

yaa, Thanks BTW
