### ISSUE TITLE
The crypto exchange has stopped opening

### ISSUE THREAD

**Issue by authorless** [mikropsoft/StevenBlock#9]
I faced such a problem that in the latest version of the module, the MEXC crypto exchange stopped opening. Some links may have been affected and now the site just won't load. Tell me how to fix this problem.

**Comment by mikropsoft** [comment]
> I faced such a problem that in the latest version of the module, the MEXC crypto exchange stopped opening. Some links may have been affected and now the site just won't load. Tell me how to fix this problem. 

You can check if the domain of the website is listed by installing a hosts editor. Alternatively, you can try again by installing the 1hosts version.

**Comment by mikropsoft** [comment]
I installed the same application and it works fine for me without any issues.
